spring.threads.virtual.enabled=true

# 1. 원장 DB 접속 정보
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. 로그인 DB 접속 정보(ReadOnly)
auth.datasource.url=${AUTH_DATASOURCE_URL}
auth.datasource.username=${AUTH_DATASOURCE_USERNAME}
auth.datasource.password=${AUTH_DATASOURCE_PASSWORD}
auth.datasource.driver-class-name=org.postgresql.Driver
# 로그인 DB의 접속 경합을 예방하기 위해 커넥션 풀 고정
auth.datasource.hikari.maximum-pool-size=3